Repository sharemindteam/sharemind-client, pull requests merged in 2023-11, with the labels that each got.

#4 [Feature] v0 상담 신청, 결제 완료, 결제 비밀번호, 평가 페이지
  src/Router.tsx
  src/assets/images/Rating/EmptyStar.svg
  src/assets/images/Rating/Star.svg
  src/components/CounselLink/CounselLinkHeader.tsx
  src/components/CounselLink/PwInput.tsx
  src/components/CounselLink/index.ts
  src/components/Payment/PaymentContent.tsx
  src/components/Payment/PaymentHeader.tsx
  src/components/Payment/index.ts
  src/components/Rating/RatingHeader.tsx
  src/components/Rating/RatingReview.tsx
  src/components/Rating/StarRate.tsx
  src/components/Rating/index.ts
  src/components/request/EmailInput.tsx
  src/components/request/RequestHeader.tsx
  src/components/request/index.ts
  src/pages/CounselLinkPage.tsx
  src/pages/PaymentPage.tsx
  src/pages/RatingPage.tsx
  src/pages/RequestPage.tsx
Labels: Feature, Style

#5 [Feature] 채팅 페이지 구현
  src/Router.tsx
  src/components/Chatting/CautionModal.tsx
  src/components/Chatting/ChatBubble.tsx
  src/components/Chatting/ChatHeader.tsx
  src/components/Chatting/ChatInput.tsx
  src/components/Chatting/index.ts
  src/components/CounselLink/CounselLinkHeader.tsx
  src/pages/AdminPage.tsx
  src/pages/ChatRoomPage.tsx
Labels: Feature, Style

#11 [Bug] 반응형 수정 및 첫 렌더 시 vh 안맞는 bug 수정
  src/components/Chatting/ChatHeader.tsx
  src/components/Payment/PaymentContent.tsx
  src/components/Rating/RatingHeader.tsx
  src/components/Rating/RatingReview.tsx
  src/components/Rating/StarRate.tsx
  src/pages/RatingPage.tsx
  src/styles/GlobalStyle.ts
Labels: Bug, Style

#17 [Feature] admin 페이지, review 페이지 구현완료
  src/Router.tsx
  src/components/Admin/PayCheckModal.tsx
  src/components/Admin/PwAdminInput.tsx
  src/components/Admin/UnpaidItem.tsx
  src/components/Admin/UnpaidList.tsx
  src/components/Rating/RatingReview.tsx
  src/index.tsx
  src/pages/AdminPage.tsx
  src/pages/RatingPage.tsx
  src/utils/atom.tsx
Labels: Feature
