Repository sharemindteam/sharemind-client, pull requests merged in 2024-07, with the labels that each got.

#330 [Feat] 결제 안내 페이지 레이아웃 수정
  src/components/Buyer/BuyerPaymentDetail/PaymentDetailInfo.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/components/Common/AppContainer.tsx
  src/pages/Buyer/BuyerOpenPaymentDetail.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
Labels: Feature, Style, Priority-1 🔥, Stage-2/code-review-request

#331 [Feat] 베타 테스트 안내 페이지 레이아웃 구현
  src/pages/Buyer/BuyerFinishPayment.tsx
Labels: Style, Priority-1 🔥, Stage-2/code-review-request

#333 fix: add exception for location state
  src/components/Buyer/BuyerLetter/LetterMainSection.tsx
Labels: Bug, Priority-1 🔥

#332 Feat/minder profile layout 329
  src/components/Buyer/BuyerCounselorProfile/CounselorExp.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorProfileCard.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorProfileNav.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorTypeSection.tsx
  src/components/Buyer/BuyerCounselorProfile/index.ts
  src/components/Common/AppContainer.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/utils/convertTimeToString.ts
  src/utils/type.ts
Labels: Style, Stage-2/code-review-request

#336 [Feat] beta 로고 적용
  src/assets/logo/beta_logo.png
  src/components/Common/Header.tsx
Labels: Style, Priority-1 🔥, Stage-2/code-review-request

#337 [Feat] 구매, 고객센터 링크 연결
  src/Router.tsx
  src/components/Common/HomeAboutFooterSection.tsx
  src/components/Common/Profile.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerOpenPaymentDetail.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
Labels: Feature, Stage-2/code-review-request

#338 [Chore] 수익 관리 subtitle 삭제
  src/components/Seller/SellerCalculateManagement/NoCalculationGraphic.tsx
Labels: Stage-2/code-review-request, Chore

#340 [Hotfix] 마인더 홈 헤더에서 셰어마인드 베타로고 첨부
  src/components/Common/Header.tsx
Labels: Bug, Style, Priority-1 🔥, Stage-2/code-review-request

#346 [Feat] husky로 commit 시 이슈 넘버 자동할당하는 로직 추가
  addIssueNumber.sh
  package-lock.json
  package.json
Labels: Feature, Setting, Priority-2, Stage-2/code-review-request

#343 feat: add clarity tag
  public/index.html
Labels: Feature, Priority-1 🔥

#345 [Feat] 변경된 Counselor card layout 반영
  src/api/delete.ts
  src/api/patch.ts
  src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
  src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
  src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
  src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorCard.tsx
  src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorResults.tsx
  src/components/Buyer/BuyerSearchResult/SearchResults.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/components/Common/CounselorCard.tsx
  src/utils/type.ts
Labels: Feature, Style, Priority-1 🔥, Stage-2/code-review-request

#349 [Feat] 들준마, 카테고리 검색 페이지 empty view 추가
  src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
  src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/utils/type.ts
Labels: Priority-2, Stage-2/code-review-request, Chore

#353 chore: change resize hook location (#352)
  src/App.Layout.tsx
  src/components/Common/AppContainer.tsx
Labels: Style, Priority-1 🔥, Stage-2/code-review-request

#355 [Hotfix] 편지, 채팅 가격 설정 범위 수정
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/pages/Seller/SellerMyPageModifyProfile.tsx
Labels: Bug, Priority-1 🔥, Stage-2/code-review-request, Chore

#358 [Hotfix] 홈화면 들준마 레이아웃 모바일 깨짐 수정
  src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
  src/components/Common/CounselorCard.tsx
  src/pages/Buyer/BuyerHome.tsx
Labels: Bug, Stage-2/code-review-request

#351 [Feat] 찜 목록 페이지 infinite query로 마이그레이션
  .github/ISSUE_TEMPLATE/feature.md
  src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorResults.tsx
  src/components/Buyer/BuyerSavedCounselor.tsx/SavedOpenConsultResults.tsx
  src/components/Common/CounselorCard.tsx
  src/pages/Buyer/BuyerSavedCounselor.tsx
Labels: Refactor, Stage-2/code-review-request, Chore

#359 feat: remove optional condition to counselor card `totalConsult` (#348)
  src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorResults.tsx
  src/components/Common/CounselorCard.tsx
  src/utils/type.ts
Labels: API, Feature, Priority-2, Stage-2/code-review-request

#366 [Feature] Payapp 결제 api 연동
  public/index.html
  src/global.d.ts
  src/pages/Buyer/BuyerPaymentDetail.tsx
  src/utils/requestPayment.ts
  src/utils/type.ts
Labels: API, Priority-1 🔥, Stage-2/code-review-request

#368 [Hotfix] 7월 29일 수정사항 2가지
  src/pages/Buyer/BuyerOpenPaymentDetail.tsx
  src/utils/requestPayment.ts
Labels: Bug
