Repository sharemindteam/sharemind-client, pull requests merged in 2024-04, with the labels that each got.

#200 [Feature] 불필요한 subscribe 예외처리
  src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
  src/components/Seller/SellerConsult/SellerChatList.tsx
  src/utils/atom.ts
Labels: Feature, Refactor, Priority-4

#202 refactor: change to cookie
  src/api/axios.ts
  src/components/Buyer/BuyerQuit/QuitFooter.tsx
  src/contexts/StompContext.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerLogout.tsx
  src/pages/Buyer/BuyerPwChange.tsx
  src/pages/Seller/SellerLogout.tsx
Labels: Refactor, Priority-4, Stage-2/code-review-request

#203 [Feature] 비밀번호 변경 useDebounce 적용 및 버그 개선
  package-lock.json
  package.json
  src/components/Buyer/BuyerPwChange/usePwChangeInput.ts
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Buyer/BuyerPwChange.tsx
  src/utils/signupValidCheck.ts
Labels: Bug, API, Feature, Priority-2, Stage-2/code-review-request

#207 [Feature] websocket 백엔드 변경 사항 반영
  src/api/get.ts
  src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
  src/components/Seller/SellerConsult/SellerChatList.tsx
Labels: Feature, Priority-1 🔥, Stage-2/code-review-request

#213 [Hotfix] 판매 정보 수정 페이지 모달 backdrop 클릭 시 close 되도록 수정
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileHeader.tsx
  src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
  src/pages/Seller/SellerMyPageModifyProfile.tsx
Labels: Bug, Priority-3, Stage-2/code-review-request

#214 [Hotfix] 모바일 상담 탭 카드 텍스트 짤림 이슈 해결
  src/components/Buyer/Common/ConsultCard.tsx
  src/components/Seller/Common/OngoingCounsultBox.tsx
Labels: Bug, Style, Priority-1 🔥, Stage-2/code-review-request

#216 [Refactor] chat 페이지 코드 가독성 개선 리펙토링
  src/Router.tsx
  src/api/.gitkeep
  src/assets/.gitkeep
  src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
  src/components/Buyer/BuyerChat/BuyerChatFooter.tsx
  src/components/Buyer/BuyerChat/BuyerChatSection.tsx
  src/components/Buyer/BuyerConsult/BuyerConsultChatSection.tsx
  src/components/Buyer/BuyerConsult/BuyerConsultLetterSection.tsx
  src/components/Seller/SellerChat/ChatAlertModal.tsx
  src/components/Seller/SellerChat/ChatBottomSection.tsx
  src/components/Seller/SellerChat/ChatHeader.tsx
  src/components/Seller/SellerChat/ChatListSection.tsx
  src/components/Seller/SellerChat/ChatReportModal.tsx
  src/components/Seller/SellerChat/ChatStartRequestModal.tsx
  src/components/Seller/SellerChat/SellerChatFooter.tsx
  src/components/Seller/SellerChat/SellerChatSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/CategoryModal.tsx
  src/components/Seller/SellerMyPageModifyProfile/IsOutPopup.tsx
  src/components/Seller/SellerMyPageModifyProfile/StyleModal.tsx
  src/components/Seller/SellerMyPageModifyProfile/UpdatePopup.tsx
  src/hooks/Chat/useChatRequestTime.ts
  src/hooks/useTokenRefresh.tsx
  src/pages/.gitkeep
  src/pages/Buyer/.gitkeep
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Seller/SellerChat.tsx
  src/pages/Seller/SellerChatTemp.tsx
  src/styles/.gitkeep
  src/utils/.gitkeep
  src/utils/LoadingSpinner.tsx
  src/utils/ScrollToTop.tsx
  src/utils/buyerDummy.ts
Labels: Refactor, Priority-3, Stage-2/code-review-request

#217 [Feature] 홈화면에서도 채팅이 업데이트되도록 구현
  src/App.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/contexts/StompContext.tsx
  src/pages/Buyer/BuyerMypage.tsx
Labels: Feature, Priority-2, Stage-2/code-review-request

#226 [QA] 공개 상담 작성 페이지 모바일 짤림 이슈 해결
  src/pages/Buyer/BuyerWriteOpenConsult.tsx
Labels: Bug, Style, Stage-2/code-review-request

#227 [Fix] 공개상담 제목, 본문 최대 입력 글자 수 제한, 헤더 고정
  src/components/Buyer/BuyerWriteOpenConsult/FianlWritePopup.tsx
  src/components/Common/Header.tsx
  src/components/Common/TabA1.tsx
  src/components/Seller/SellerMyPageReview/SellerReviewHeader.tsx
  src/components/Seller/SellerMyPageViewProfile/NoProfileSection.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileHeader.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
  src/pages/Buyer/BuyerSavedCounselor.tsx
  src/pages/Buyer/BuyerWriteOpenConsult.tsx
  src/pages/Seller/SellerConsult.tsx
  src/pages/Seller/SellerHome.tsx
  src/pages/Seller/SellerMyPageReview.tsx
  src/pages/Seller/SellerMyPageViewProfile.tsx
  src/utils/convertStringToCharNum.ts
Labels: Bug, Feature

#229 [Hotfix] 공개상담 댓글 썻을 경우 버튼 비활성화 + 추가적으로 자잘한 것 2가지 구현
  src/api/get.ts
  src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
  src/components/Common/Profile.tsx
  src/components/Seller/Common/BankSelectModal.tsx
  src/components/Seller/SellerOpenConsult/BottomSection.tsx
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Seller/SellerMypage.tsx
  src/pages/Seller/SellerRefundBankAccount.tsx
Labels: Bug, API, Feature

#235 [Hotfix] 서비스 소개 페이지 navigate 처리
  src/pages/Common/Service.tsx
Labels: Feature, Stage-2/code-review-request

#234 [Hotfix] 채팅 새로고침 시 끊기는 이슈 해결 및 ws 로직 개선
  src/components/Buyer/BuyerConsult/BuyerConsultChatSection.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Seller/SellerConsult/SellerChatList.tsx
  src/contexts/StompContext.tsx
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Seller/SellerChat.tsx
  src/utils/constant.ts
Labels: Bug, Priority-1 🔥, Stage-2/code-review-request

#238 [Hotfix] 최근 검색어 클릭 시 쿼리 파라미터로써 keyword 추가, 인증되지 않은 경우 공개상담 탭 접근 막고 alert 띄우기
  src/components/Buyer/BuyerSearch/SearchRecent.tsx
  src/components/Common/Header.tsx
  src/components/Common/Profile.tsx
  src/components/Common/TabA1.tsx
  src/components/Seller/SellerHome/ConsultReviewsSection.tsx
  src/components/Seller/SellerMyPageReview/SellerReviewHeader.tsx
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/pages/Seller/SellerMyPageViewProfile.tsx
  src/utils/isIncludeSpecialLetter.ts
Labels: Bug

#244 [Hotfix] 공개상담 댓글 목록 줄바꿈 반영 및 헤더 고정
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerOpenConsult/HotOpenConsultList.tsx
  src/components/Buyer/BuyerOpenConsultDetail/CommentCard.tsx
  src/components/Common/TabB2.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerOpenConsult/CommentListSection.tsx
  src/pages/Seller/SellerOpenConsult.tsx
Labels: Bug

#245 [Hotfix] 시간 선택 모달 디바이스에 따라 스타일 깨짐 오류
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerOpenConsult/HotOpenConsultList.tsx
  src/components/Buyer/BuyerOpenConsultDetail/CommentCard.tsx
  src/components/Common/TabB2.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
  src/components/Seller/SellerOpenConsult/CommentListSection.tsx
  src/pages/Seller/SellerOpenConsult.tsx
Labels: Bug

#253 chore: remove unusing imports
  src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
  src/components/Buyer/BuyerConsult/ConsultModal.tsx
  src/components/Buyer/BuyerConsult/IsBuyPopup.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerLetterWrite/LetterSaveModal.tsx
  src/components/Buyer/BuyerLetterWrite/LetterWriteModal.tsx
  src/components/Buyer/BuyerQuit/QuitReasonsBox.tsx
  src/components/Buyer/BuyerReviewManage/ReviewWroteCard.tsx
  src/components/Buyer/BuyerSavedCounselor.tsx/SavedOpenConsultCard.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/components/Buyer/BuyerWriteOpenConsult/FinalSavePopup.tsx
  src/components/Common/TagLetterStatus.tsx
  src/components/Seller/SellerCalculateManagement/NoCalculationGraphic.tsx
  src/components/Seller/SellerHome/IncomeManagementSection.tsx
  src/components/Seller/SellerHome/OnGoingConsultSection.tsx
  src/components/Seller/SellerLetter/LetterBonusQuestionStep.tsx
  src/components/Seller/SellerLetter/LetterBonusReplyStep.tsx
  src/components/Seller/SellerLetter/LetterComplaintMenu.tsx
  src/components/Seller/SellerLetter/LetterHeader.tsx
  src/components/Seller/SellerLetter/LetterQuestionStep.tsx
  src/components/Seller/SellerLetter/LetterTagListSection.tsx
  src/components/Seller/SellerLetterWrite/LetterPostModal.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteHeader.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
  src/components/Seller/SellerMyPageModifyProfile/TypeModal.tsx
  src/components/Seller/SellerMyPageReview/ReviewCard.tsx
  src/components/Seller/SellerMyPageReview/ReviewComplaintMenu.tsx
  src/components/Seller/SellerMyPageReview/SellerReviewHeader.tsx
  src/components/Seller/SellerMyPageReview/SellerReviewMainSection.tsx
  src/components/Seller/SellerMyPageViewProfile/NoProfileSection.tsx
  src/components/Seller/SellerOpenConsult/IsSendPopup.tsx
  src/components/Seller/SellerOpenConsult/OpenConsultHeader.tsx
  src/components/Seller/SellerVerifyMaterial/FinalMaterial.tsx
  src/components/Seller/SellerVerifyMaterial/SecondMaterial.tsx
  src/components/Seller/SellerVerifyMaterial/ThirdMaterial.tsx
  src/components/Seller/SellerVerifyMaterial/VerifyMaterialHeader.tsx
  src/components/Seller/SellerVerifyQuiz/IsSubmitQuizModal.tsx
  src/components/Seller/SellerVerifyQuiz/VerifyQuizButton.tsx
  src/pages/Buyer/BuyerFinishPayment.tsx
  src/pages/Buyer/BuyerOpenConsultRequest.tsx
  src/pages/Buyer/BuyerQuit.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Seller/SellerLetter.tsx
  src/pages/Seller/SellerVerifyMaterial.tsx
  src/pages/Seller/SellerVerifyQuiz.tsx
Labels: Refactor, Stage-2/code-review-request

#260 [Hotfix] 셰어 사이드 uread count 안보이는 이슈
  src/components/Buyer/BuyerConsult/BuyerConsultChatSection.tsx
  src/components/Buyer/Common/ConsultCard.tsx
Labels: Bug, Priority-1 🔥, Stage-2/code-review-request

#258 [Hotfix] 리뷰 줄바꿈 처리 안되는 이슈 해결
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
Labels: Bug, Priority-1 🔥, Stage-2/code-review-request

#255 [Hotfix] 상담 종료시 상담 카드 리뷰 안뜨는 이슈 수정
  src/components/Buyer/Common/ConsultCard.tsx
Labels: Bug, Priority-1 🔥, Stage-2/code-review-request

#252 [Refactor] 사용가능한 상담 방식만 선택할 수 있게 수정
  src/Router.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorProfileHeader.tsx
  src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorCard.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/pages/Buyer/BuyerConsultRequest.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
Labels: Refactor, Priority-2, Stage-2/code-review-request

#256 [Hotfix] 이용 가능한 상담 방식에 대한 요금만 보이도록 수정
  src/components/Buyer/BuyerCounselorProfile/CounselorExp.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
Labels: Feature, Priority-1 🔥, Stage-2/code-review-request

#263 feat: apply inactive when chat is finished (#262)
  src/components/Buyer/BuyerChat/BuyerChatSection.tsx
  src/pages/Buyer/BuyerChat.tsx
Labels: Feature, Priority-1 🔥, Stage-2/code-review-request

#267 [Feature] 마인더 홈화면 ws 연결 및 stomp provider 개선
  src/components/Seller/SellerHome/OnGoingConsultSection.tsx
  src/contexts/StompContext.tsx
Labels: Feature, Priority-1 🔥, Stage-2/code-review-request

#274 [Refactor] 셰어 홈 진행중인 상담에서도 stomp subscription을 이용하여 연결을 관리합니다.
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Seller/SellerHome/OnGoingConsultSection.tsx
Labels: Refactor, Priority-1 🔥, Stage-2/code-review-request, WebSocket
