Repository sharemindteam/sharemind-client, pull requests merged in 2024-06, with the labels that each got.

#293 Refactor/simplify signup find info 291
  src/api/patch.ts
  src/components/Buyer/BuyerFindInfo/FindInfoNav.tsx
  src/components/Buyer/BuyerSignup/SignupInfo.tsx
  src/components/Buyer/BuyerSignup/SignupPw.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/pages/Buyer/BuyerFindInfo.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerSignup.tsx
Labels: API, Feature, Priority-2, Stage-2/code-review-request

#299 [Chore] 퀴즈 변경된 텍스트 반영과 간단한 리팩토링
  src/Router.tsx
  src/components/Seller/SellerVerifyQuiz/IsStopQuizModal.tsx
  src/components/Seller/SellerVerifyQuiz/IsSubmitQuizModal.tsx
  src/components/Seller/SellerVerifyQuiz/VerifyFail.tsx
  src/components/Seller/SellerVerifyQuiz/VerifyQuizHeader.tsx
  src/components/Seller/SellerVerifyQuiz/VerifySuccess.tsx
  src/pages/Buyer/BuyerOpenConsult.tsx
  src/pages/Seller/SellerVerifyQuiz.tsx
  src/utils/constant.ts
Labels: Refactor, Chore

#301 [Bug] /minder URL경로 접속 시 로그인으로 리다이렉트되는 문제 해결
  src/api/axios.ts
  src/contexts/StompContext.tsx
Labels: Bug

#305 [Hotfix] 배경 이미지 레이아웃 깨짐 수정
  src/App.Layout.tsx
Labels: Bug, Style, Priority-1 🔥, Stage-2/code-review-request

#308 [Feature] 리뉴얼된 디자인 반영 및 각종 아이콘/그래픽 통일성 부여
  src/Router.tsx
  src/assets/icons/graphic-noting.svg
  src/assets/icons/icon-heart2.svg
  src/assets/icons/icon-save1.svg
  src/assets/icons/icon-save2.svg
  src/assets/icons/search.svg
  src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
  src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
  src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
  src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
  src/components/Buyer/BuyerSearch/SearchHeader.tsx
  src/components/Buyer/BuyerSearchResult/SearchResults.tsx
  src/components/Buyer/BuyerWriteOpenConsult/FianlWritePopup.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/components/Common/Header.tsx
  src/components/Seller/Common/BankSelectModal.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/pages/Seller/SellerAccountSetting.tsx
  src/pages/Seller/SellerProfitBankAccount.tsx
  src/utils/getCurrentHour.ts
  src/utils/type.ts
Labels: Bug, API, Feature, Priority-1 🔥, Chore

#309 [0624 배포]
  src/App.Layout.tsx
  src/Router.tsx
  src/assets/icons/graphic-noting.svg
  src/assets/icons/icon-heart2.svg
  src/assets/icons/icon-save1.svg
  src/assets/icons/icon-save2.svg
  src/assets/icons/search.svg
  src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
  src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
  src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
  src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
  src/components/Buyer/BuyerSearch/SearchHeader.tsx
  src/components/Buyer/BuyerSearchResult/SearchResults.tsx
  src/components/Buyer/BuyerWriteOpenConsult/FianlWritePopup.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/components/Common/Header.tsx
  src/components/Seller/Common/BankSelectModal.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/pages/Seller/SellerAccountSetting.tsx
  src/pages/Seller/SellerProfitBankAccount.tsx
  src/utils/getCurrentHour.ts
  src/utils/type.ts
Labels: API, Priority-1 🔥

#310 [Feat] 구글 애널리틱스 반영
  public/index.html
Labels: Feature, Stage-2/code-review-request

#311 [Feat] meta 태그 title, description 변경
  public/index.html
Labels: Stage-2/code-review-request

#320 [Bug] 공개상담 detail 페이지(인기순/최신순) 헤더 스크롤 시 사라지는 이슈 해결
  src/components/Common/AppHeader.tsx
  src/styles/AppStyle.ts
Labels: Bug, Feature, Style, Priority-2, Stage-2/code-review-request

#319 [Feat] empty section 공통 컴포넌트 구현 및 결제내역, 리뷰 내역에 적용
  src/components/Common/EmptySection.tsx
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
Labels: Feature, Priority-2, Stage-2/code-review-request

#322 [Feat] 셰어 편지 종료 시 리뷰 작성하기 버튼 추가
  src/components/Buyer/BuyerConsult/BuyerConsultLetterSection.tsx
  src/components/Buyer/BuyerLetter/LetterMainSection.tsx
  src/components/Buyer/Common/ConsultCard.tsx
Labels: Feature, Priority-2, Stage-2/code-review-request
