Repository sharemindteam/sharemind-client, pull requests merged in 2024-02, with the labels that each got.

#128 [Feature] 검색 관련 무한 스크롤 구현 및 홈 url /share로 이동
  src/Router.tsx
  src/api/get.ts
  src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerSearch/SearchHeader.tsx
  src/components/Buyer/BuyerSearchResult/SearchResults.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/components/Common/AppContainer.tsx
  src/components/Common/TabA1.tsx
  src/pages/Buyer/BuyerAvailCounselor.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerPaymentComplete.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Buyer/BuyerSavedCounselor.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
  src/pages/Buyer/BuyerSignupComplete.tsx
  src/pages/Common/Service.tsx
Labels: API, Feature

#129 [Feature]검색 관련 무한 스크롤 구현 및 홈 url /share로 이동
  src/Router.tsx
  src/api/get.ts
  src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerSearch/SearchHeader.tsx
  src/components/Buyer/BuyerSearchResult/SearchResults.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/components/Common/AppContainer.tsx
  src/components/Common/TabA1.tsx
  src/pages/Buyer/BuyerAvailCounselor.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerPaymentComplete.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Buyer/BuyerSavedCounselor.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
  src/pages/Buyer/BuyerSignupComplete.tsx
  src/pages/Common/Service.tsx
Labels: API, Feature

#130 [Feature] 무한스크롤 구현완료 외 자잘
  src/Router.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerPayment/PaymentCard.tsx
  src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorResults.tsx
  src/components/Buyer/Common/SortModal.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Buyer/BuyerSavedCounselor.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
  src/utils/pending.ts
  src/utils/type.ts
Labels: API, Feature

#131 [Feature] 무한스크롤 구현완료 외 자잘
  src/Router.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerPayment/PaymentCard.tsx
  src/components/Buyer/BuyerSavedCounselor.tsx/SavedCounselorResults.tsx
  src/components/Buyer/Common/SortModal.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Buyer/BuyerSavedCounselor.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
  src/utils/pending.ts
  src/utils/type.ts
Labels: Bug, API, Feature

#132 [Feature] 수익 관리 api 연결, 그 외 자잘한 반영사항들
  src/App.tsx
  src/api/get.ts
  src/api/patch.ts
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerHome/IncomeManagementSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
  src/components/Seller/SellerMyPageReview/SellerReviewMainSection.tsx
  src/components/Seller/SellerVerifyQuiz/VerifySuccess.tsx
  src/pages/Seller/SellerCalculateManagement.tsx
  src/pages/Seller/SellerMypage.tsx
Labels: API, Style

#134 [Fix] 들준마페이지 props 오류 해결
  src/pages/Buyer/BuyerAvailCounselor.tsx
  src/pages/Buyer/BuyerConsult.tsx
Labels: Bug, API

#135 [Fix] 들준마페이지 props 오류 해결
  src/pages/Buyer/BuyerAvailCounselor.tsx
  src/pages/Buyer/BuyerConsult.tsx
Labels: Bug, API

#138 [Fix] 마인더 프로필 줄바꿈 추가 (#46)
  src/components/Buyer/BuyerCounselorProfile/CounselorExp.tsx
Labels: Bug, Feature

#139 [Fix] 마인더 프로필 줄바꿈 추가 (#46)
  src/components/Buyer/BuyerCounselorProfile/CounselorExp.tsx
Labels: Bug, Feature

#140 [Feature] 무한 스크롤 중복 api 호출 문제 fix 및 무한 스크롤 최종완료
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/Common/SortModal.tsx
  src/hooks/useDebounce.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/Buyer/BuyerAvailCounselor.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Buyer/BuyerSavedCounselor.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
Labels: Bug, API, Feature

#144 [Feature] 계정탈퇴 페이지 구현완료 및 비밀번호 입력 max length로 막아둔 오류 fix
  public/index.html
  src/App.tsx
  src/Router.tsx
  src/api/axios.ts
  src/api/delete.ts
  src/api/get.ts
  src/api/patch.ts
  src/assets/icons/chat-send-button.svg
  src/assets/icons/icon-heart1.svg
  src/components/Buyer/BuyerChat/ChatStartRequestBox.tsx
  src/components/Buyer/BuyerFindInfo/FindInfoIdModal.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerLetterWrite/LetterWriteModal.tsx
  src/components/Buyer/BuyerQuit/QuitBody.tsx
  src/components/Buyer/BuyerQuit/QuitFooter.tsx
  src/components/Buyer/BuyerQuit/QuitReasonsBox.tsx
  src/components/Buyer/BuyerSignup/SignupInfo.tsx
  src/components/Buyer/BuyerSignup/SignupPw.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/components/Buyer/Common/ConsultCard.tsx
  src/components/Buyer/Common/PwInput.tsx
  src/components/Common/AppContainer.tsx
  src/components/Common/Input.tsx
  src/pages/Buyer/BuyerAccountSetting.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Buyer/BuyerChatTest.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerFindInfo.tsx
  src/pages/Buyer/BuyerLetterWrite.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerLogout.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerPwChange.tsx
  src/pages/Buyer/BuyerQuit.tsx
  src/pages/Buyer/BuyerTerminate.tsx
  src/pages/Seller/SellerPwChange.tsx
  src/styles/color.ts
  src/utils/atom.ts
  src/utils/constant.ts
  src/utils/type.ts
Labels: Bug, API, Feature, Style

#145 [Feature] QA 전 notification 제외 채팅 구현완료
  package-lock.json
  package.json
  src/Router.tsx
  src/api/get.ts
  src/components/Buyer/BuyerChat/ChatCounselorInfoBox.tsx
  src/components/Buyer/BuyerChat/ChatStartRequestBox.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Common/AppContainer.tsx
  src/components/Seller/SellerChatTemp/ChatAlertModal.tsx
  src/components/Seller/SellerChatTemp/ChatReportModal.tsx
  src/components/Seller/SellerChatTemp/ChatStartRequestModal.tsx
  src/hooks/useChat.ts
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Buyer/BuyerChatTest.tsx
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Seller/SellerChatTemp.tsx
  src/styles/GlobalStyle.ts
  src/utils/AppendCategoryType.ts
  src/utils/convertDate.ts
  src/utils/pending.ts
  src/utils/type.ts
Labels: Bug, API, Feature, Style

#146 [Feature] QA 전 notification 제외 채팅 기능 추가 구현
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/Router.tsx
  src/api/axios.ts
  src/api/delete.ts
  src/api/get.ts
  src/api/patch.ts
  src/assets/icons/chat-send-button.svg
  src/assets/icons/icon-heart1.svg
  src/components/Buyer/BuyerChat/ChatCounselorInfoBox.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerFindInfo/FindInfoIdModal.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerLetterWrite/LetterWriteModal.tsx
  src/components/Buyer/BuyerQuit/QuitBody.tsx
  src/components/Buyer/BuyerQuit/QuitFooter.tsx
  src/components/Buyer/BuyerQuit/QuitReasonsBox.tsx
  src/components/Buyer/BuyerSignup/SignupInfo.tsx
  src/components/Buyer/BuyerSignup/SignupPw.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/components/Buyer/Common/ConsultCard.tsx
  src/components/Buyer/Common/PwInput.tsx
  src/components/Buyer/Common/SortModal.tsx
  src/components/Common/AppContainer.tsx
  src/components/Common/Input.tsx
  src/components/Seller/SellerChatTemp/ChatAlertModal.tsx
  src/components/Seller/SellerChatTemp/ChatReportModal.tsx
  src/components/Seller/SellerChatTemp/ChatStartRequestModal.tsx
  src/hooks/useChat.ts
  src/hooks/useDebounce.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/Buyer/BuyerAccountSetting.tsx
  src/pages/Buyer/BuyerAvailCounselor.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerFindInfo.tsx
  src/pages/Buyer/BuyerLetterWrite.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerLogout.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Buyer/BuyerPwChange.tsx
  src/pages/Buyer/BuyerQuit.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Buyer/BuyerSavedCounselor.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
  src/pages/Buyer/BuyerTerminate.tsx
  src/pages/Seller/SellerChatTemp.tsx
  src/pages/Seller/SellerPwChange.tsx
  src/styles/GlobalStyle.ts
  src/styles/color.ts
  src/utils/AppendCategoryType.ts
  src/utils/atom.ts
  src/utils/constant.ts
  src/utils/convertDate.ts
  src/utils/pending.ts
  src/utils/type.ts
Labels: Bug, API, Feature, Style
