Repository sharemindteam/sharemind-client, pull requests merged in 2024-11, with the labels that each got.

#415 마인더 정산신청 페이지 무한스크롤 오류 해결 및 DTO 업데이트
  src/Router.tsx
  src/components/Seller/SellerCalculateManagement/CompleteApplyPopup.tsx
  src/components/Seller/SellerCalculateManagement/SellerCalculateCard.tsx
  src/pages/Seller/SellerCalculateManagement.tsx
Labels: Bug, API

#417 Hotfix/clarity error 416
  package-lock.json
  package.json
  public/index.html
  src/index.tsx
Labels: Bug

#418 1106 배포
  package-lock.json
  package.json
  public/index.html
  src/Router.tsx
  src/components/Seller/SellerCalculateManagement/CompleteApplyPopup.tsx
  src/components/Seller/SellerCalculateManagement/SellerCalculateCard.tsx
  src/index.tsx
  src/pages/Seller/SellerCalculateManagement.tsx
Labels: Deploy
