Repository sharemindteam/sharemind-client, pull requests merged in 2024-03, with the labels that each got.

#151 판매자 채팅,편지 목록 컴포넌트 분리 완료
  README.md
  package-lock.json
  package.json
  src/components/Seller/SellerConsult/SellerChatList.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerConsult/SellerLetterList.tsx
Labels: Refactor

#157 [Refactor] DTO 업데이트 및 버튼 사용성 개선
  src/components/Buyer/BuyerFindInfo/FindInfoIdModal.tsx
  src/components/Buyer/BuyerSignup/SignupInfo.tsx
  src/pages/Buyer/BuyerFindInfo.tsx
Labels: Refactor

#163 [Feature] 마인더 진행중인 상담 api 연동 오류 해결
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerHome/OnGoingConsultSection.tsx
Labels: Bug

#166 [Hotfix] connect when login
  src/contexts/StompContext.tsx
  src/pages/Buyer/BuyerLogin.tsx
Labels: Bug

#167 [Feature] 마인더 리뷰 무한 스크롤 구현
  src/components/Seller/SellerMyPageReview/ReviewCard.tsx
  src/components/Seller/SellerMyPageReview/ReviewComplaintMenu.tsx
  src/components/Seller/SellerMyPageReview/SellerReviewMainSection.tsx
Labels: Feature

#170 feat: maintain focus when submit
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Seller/SellerChatTemp.tsx
Labels: Bug

#172 [Feature] 소개 페이지 무한 가로 스크롤 구현
  src/pages/Common/Service.tsx
Labels: Feature, Style

#173 hotfix: maintain keyboard submit
  .github/pull_request_Template.md
  src/contexts/StompContext.tsx
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Seller/SellerChatTemp.tsx
Labels: Bug, Priority-1 🔥

#174 chore: find pw modal text
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/pages/Buyer/BuyerFindInfo.tsx
  src/pages/Buyer/BuyerPwChange.tsx
Labels: Bug, Priority-4

#177 hotfix: buyer consult empty missing
  .github/ISSUE_TEMPLATE/bug.md
  src/components/Buyer/BuyerConsult/BuyerLetterSection.tsx
Labels: Bug, Style

#181 feat: insert new chat at top on consult tab (#178)
  src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
  src/components/Seller/SellerConsult/SellerChatList.tsx
Labels: API, Feature, Priority-2

#183 Feat/disconnect logout
  src/api/patch.ts
  src/pages/Buyer/BuyerLogout.tsx
  src/pages/Seller/SellerLogout.tsx
Labels: API, Feature, Priority-2

#187 docs: edit pr template
  .github/pull_request_Template.md
Labels: Docs, Priority-4

#188 [Refactor] 셰어/마인더 상담 목록 페이지 뷰 쿼리스트링 상태에 맞게 매칭
  src/Router.tsx
  src/assets/icons/icon-comment.svg
  src/assets/icons/icon-heart3.svg
  src/assets/icons/icon-lock.svg
  src/assets/icons/icon-save3.svg
  src/assets/icons/underline-big.svg
  src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
  src/components/Buyer/BuyerConsult/ConsultModal.tsx
  src/components/Common/TabA1.tsx
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerConsult/SellerChatList.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerConsult/SellerLetterList.tsx
  src/components/Seller/SellerConsult/SellerOpenConsultList.tsx
  src/components/Seller/SellerOpenConsult/MainQuestionSection.tsx
  src/components/Seller/SellerOpenConsult/OpenConsultHeader.tsx
  src/contexts/StompContext.tsx
  src/hooks/.gitkeep
  src/hooks/useConsultParams.ts
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerOpenConsult.tsx
  src/pages/Buyer/BuyerPwChange.tsx
  src/pages/Seller/SellerChatTemp.tsx
  src/pages/Seller/SellerMypage.tsx
  src/pages/Seller/SellerOpenConsult.tsx
Labels: Refactor

#189 feat: end consult blur
  src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
  src/components/Buyer/BuyerPayment/PaymentModal.tsx
  src/components/Buyer/Common/ConsultCard.tsx
  src/components/Seller/SellerConsult/SellerLetterList.tsx
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Common/Admin.tsx
  src/pages/Seller/SellerChatTemp.tsx
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/pages/Seller/SellerVerifyQuiz.tsx
Labels: Style, Priority-2

#190 [Sprint] 마인더 쪽 공개상담 페이지 마크업 완료
  .github/pull_request_Template.md
  src/api/patch.ts
  src/assets/icons/icon-heart3.svg
  src/assets/icons/icon-save3.svg
  src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
  src/components/Buyer/BuyerConsult/ConsultModal.tsx
  src/components/Common/TabA1.tsx
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerConsult/SellerChatList.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerConsult/SellerLetterList.tsx
  src/components/Seller/SellerConsult/SellerOpenConsultList.tsx
  src/components/Seller/SellerOpenConsult/BottomSection.tsx
  src/components/Seller/SellerOpenConsult/CommentListSection.tsx
  src/components/Seller/SellerOpenConsult/IsSendPopup.tsx
  src/components/Seller/SellerOpenConsult/MainQuestionSection.tsx
  src/components/Seller/SellerOpenConsult/OpenConsultHeader.tsx
  src/components/Seller/SellerOpenConsult/S=
  src/contexts/StompContext.tsx
  src/hooks/.gitkeep
  src/hooks/useConsultParams.ts
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerLogout.tsx
  src/pages/Buyer/BuyerPwChange.tsx
  src/pages/Seller/SellerChatTemp.tsx
  src/pages/Seller/SellerLogout.tsx
  src/pages/Seller/SellerOpenConsult.tsx
  src/utils/atom.ts
Labels: Style

#191 [Sprint] 03/25 마크업 진행사항 공유
  .github/pull_request_Template.md
  src/Router.tsx
  src/api/patch.ts
  src/assets/icons/icon-comment.svg
  src/assets/icons/icon-fire.svg
  src/assets/icons/icon-heart3.svg
  src/assets/icons/icon-lock.svg
  src/assets/icons/icon-save3.svg
  src/assets/icons/icon-write.svg
  src/assets/icons/underline-big.svg
  src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
  src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
  src/components/Buyer/BuyerConsult/ConsultModal.tsx
  src/components/Buyer/BuyerConsult/IsBuyPopup.tsx
  src/components/Buyer/BuyerOpenConsult/HotOpenConsultList.tsx
  src/components/Buyer/BuyerOpenConsult/OpenConsultList.tsx
  src/components/Buyer/BuyerWriteOpenConsult/FianlWritePopup.tsx
  src/components/Common/TabA1.tsx
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerConsult/SellerChatList.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerConsult/SellerLetterList.tsx
  src/components/Seller/SellerConsult/SellerOpenConsultList.tsx
  src/components/Seller/SellerOpenConsult/BottomSection.tsx
  src/components/Seller/SellerOpenConsult/CommentListSection.tsx
  src/components/Seller/SellerOpenConsult/IsSendPopup.tsx
  src/components/Seller/SellerOpenConsult/MainQuestionSection.tsx
  src/components/Seller/SellerOpenConsult/OpenConsultHeader.tsx
  src/contexts/StompContext.tsx
  src/hooks/.gitkeep
  src/hooks/useConsultParams.ts
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerLetterWrite.tsx
  src/pages/Buyer/BuyerLogout.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerOpenConsult.tsx
  src/pages/Buyer/BuyerOpenConsultRequest.tsx
  src/pages/Buyer/BuyerOpenPaymentDetail.tsx
  src/pages/Buyer/BuyerPwChange.tsx
  src/pages/Buyer/BuyerWriteOpenConsult.tsx
  src/pages/Seller/SellerChatTemp.tsx
  src/pages/Seller/SellerLogout.tsx
  src/pages/Seller/SellerMypage.tsx
  src/pages/Seller/SellerOpenConsult.tsx
  src/utils/atom.ts
Labels: Style

#192 hotfix: ws unsubscribe url
  src/components/Buyer/BuyerConsult/BuyerChatSection.tsx
  src/components/Seller/SellerConsult/SellerChatList.tsx
Labels: Bug, Priority-1 🔥

#194 [Style] 셰어와 마인더 스타일 통일
  src/Router.tsx
  src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Common/Profile.tsx
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerHome/ConsultReviewsSection.tsx
  src/components/Seller/SellerHome/IncomeManagementSection.tsx
  src/components/Seller/SellerHome/OnGoingConsultSection.tsx
  src/pages/.gitkeep
  src/pages/Buyer/.gitkeep
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerOpenConsultDetail.tsx
  src/pages/Seller/SellerHome.tsx
  src/utils/.gitkeep
Labels: Style

#198 feat: fix error alert
  src/pages/Buyer/BuyerPaymentDetail.tsx
Labels: Bug, API, Priority-2
