Repository sharemindteam/sharemind-client, pull requests merged in 2024-10, with the labels that each got.

#401 [Hotfix] 판매정보 확인에 전화번호 필드 추가
  src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
  src/pages/Seller/SellerMyPageViewProfile.tsx
Labels: Priority-1 🔥, Chore

#404 [Hotfix] 마인더 Letter padding으로 메세지 가리는 이슈 수정
  src/components/Seller/SellerLetter/LetterBonusQuestionStep.tsx
  src/components/Seller/SellerLetter/LetterBonusReplyStep.tsx
  src/components/Seller/SellerLetter/LetterQuestionStep.tsx
  src/components/Seller/SellerLetter/LetterReplyStep.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteHeader.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
Labels: Bug, Priority-1 🔥, Chore

#407 [Chore] 공개 상담 댓글 모달 워딩 수정
  src/components/Seller/SellerOpenConsult/IsSendPopup.tsx
Labels: Priority-1 🔥, Chore

#408 1010 배포
  src/components/Seller/SellerLetter/LetterBonusQuestionStep.tsx
  src/components/Seller/SellerLetter/LetterBonusReplyStep.tsx
  src/components/Seller/SellerLetter/LetterQuestionStep.tsx
  src/components/Seller/SellerLetter/LetterReplyStep.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteHeader.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
  src/components/Seller/SellerOpenConsult/IsSendPopup.tsx
Labels: Deploy

#409 [Hotfix] 마인더 공개상담 focus 빠지지 않는 이슈 수정
  src/components/Common/AppContainer.tsx
  src/pages/Seller/SellerOpenConsult.tsx
  src/styles/AppStyle.ts
Labels: Priority-3, Stage-2/code-review-request, Chore

#411 [Feat] 변경된 service center url 반영
  src/components/Buyer/BuyerOpenConsultDetail/CommentListSection.tsx
  src/components/Common/HomeAboutFooterSection.tsx
  src/components/Common/Profile.tsx
  src/components/Seller/SellerChat/ChatReportModal.tsx
  src/pages/Buyer/BuyerLetter.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Seller/SellerLetter.tsx
Labels: Priority-1 🔥, Stage-2/code-review-request

#412 1011 배포
  src/components/Buyer/BuyerOpenConsultDetail/CommentListSection.tsx
  src/components/Common/HomeAboutFooterSection.tsx
  src/components/Common/Profile.tsx
  src/components/Seller/SellerChat/ChatReportModal.tsx
  src/pages/Buyer/BuyerLetter.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Seller/SellerLetter.tsx
Labels: Deploy
