Repository sharemindteam/sharemind-client, pull requests merged in 2024-05, with the labels that each got.

#276 [Refactor] send 함수를 ws 디렉토리 커스텀 훅으로 리펙토링
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Seller/SellerChat.tsx
  src/ws/useCounselorChat.ts
  src/ws/useCustomerChat.ts
Labels: Refactor, Priority-2, Stage-2/code-review-request, WebSocket

#277 [Refactor] url을 통한 unsubscribe에서 StompSubscription으로 리펙토링
  src/components/Buyer/BuyerChat/BuyerChatSection.tsx
  src/components/Buyer/BuyerConsult/BuyerConsultChatSection.tsx
  src/components/Common/AppContainer.tsx
  src/components/Seller/SellerConsult/SellerChatList.tsx
  src/contexts/StompContext.tsx
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Seller/SellerChat.tsx
  src/utils/atom.ts
  src/ws/useCounselorChat.ts
  src/ws/useCustomerChat.ts
Labels: Refactor, Stage-2/code-review-request, WebSocket

#279 [QA 중간점검] 셰어, 마인더 편지 이슈 해결
  src/components/Buyer/BuyerLetterWrite/LetterPostModal.tsx
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerLetterWrite/LetterIsSaveModal.tsx
  src/components/Seller/SellerLetterWrite/LetterSavePostModal.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
Labels: Bug, API, Stage-2/code-review-request, Chore

#286 [Hotfix] 이메일 인증이 계속 눌러지는 이슈 수정
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyInput.tsx
  src/components/Common/AppContainer.tsx
  src/components/Common/Button.tsx
  src/styles/GlobalStyle.ts
Labels: Bug, Priority-2, Stage-2/code-review-request
