Repository sharemindteam/sharemind-client, pull requests merged in 2024-09, with the labels that each got.

#384 공개상담 신청, 비공개상담 결제했을 때 가이드 텍스트 수정
  src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
Labels: Chore

#389 [Chore] 상담 신청 api 로직 수정 및 일대다 상담 신청 결제 로직 수정
  src/api/post.ts
  src/pages/Buyer/BuyerOpenPaymentDetail.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
Labels: Feature, Priority-1 🔥

#390 [0910 배포]
  .github/workflows/development.yml
  .gitignore
  build.sh
  package-lock.json
  package.json
  src/api/patch.ts
  src/api/post.ts
  src/components/Buyer/BuyerConsult/BuyerOpenConsultSection.tsx
  src/components/Buyer/BuyerPaymentDetail/PaymentDetailInfo.tsx
  src/components/Common/Flex.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/UpdatePopup.tsx
  src/pages/Buyer/BuyerConsultRequest.tsx
  src/pages/Buyer/BuyerOpenPaymentDetail.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/styles/font.tsx
  src/utils/type.ts
Labels: Deploy

#392 Hotfix/payment detail 391
  src/pages/Buyer/BuyerOpenPaymentDetail.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
Labels: Bug, Priority-1 🔥, Stage-2/code-review-request

#388 [Feature] 많은 셰어에게 사랑을 받았어요, 판매정보거절페이지 작업
  src/Router.tsx
  src/api/get.ts
  src/assets/icons/right-arrow-green.svg
  src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
  src/components/Buyer/BuyerManyLovedCounselor/SearchTextHeader.tsx
  src/components/Common/Profile.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/pages/Buyer/BuyerManyLovedCounselor.tsx
  src/pages/Seller/SellerMypage.tsx
  src/pages/Seller/SellerUpdateFail.tsx
Labels: API, Feature, Style

#394 [Chore] gtag 추가
  public/index.html
Labels: Priority-1 🔥, Chore

#395 [0926 배포]
  public/index.html
  src/Router.tsx
  src/api/get.ts
  src/assets/icons/right-arrow-green.svg
  src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
  src/components/Buyer/BuyerManyLovedCounselor/SearchTextHeader.tsx
  src/components/Common/Profile.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/pages/Buyer/BuyerManyLovedCounselor.tsx
  src/pages/Buyer/BuyerOpenPaymentDetail.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
  src/pages/Seller/SellerMypage.tsx
  src/pages/Seller/SellerUpdateFail.tsx
Labels: Deploy

#397 [Hotfix] 공개상담 요청 시 phone number 오류 수정
  src/pages/Buyer/BuyerOpenConsultRequest.tsx
Labels: Bug, Priority-1 🔥

#399 [Hotfix] 마인더 편지 캐릭터 매치 안되는 이슈 수정
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
Labels: Bug, Priority-1 🔥
