Repository sharemindteam/sharemind-client, pull requests merged in 2024-01, with the labels that each got.

#3 [Feature] 기초 세팅 추가
  src/Router.tsx
  src/assets/characters/char1.svg
  src/assets/characters/char10.svg
  src/assets/characters/char11.svg
  src/assets/characters/char2.svg
  src/assets/characters/char3.svg
  src/assets/characters/char4.svg
  src/assets/characters/char5.svg
  src/assets/characters/char6.svg
  src/assets/characters/char7.svg
  src/assets/characters/char8.svg
  src/assets/characters/char9.svg
  src/pages/Buyer/BuyerHome.tsx
Labels: Style, Setting

#6 [Feature] 공통컴포넌트 수정
  package-lock.json
  package.json
  src/components/Buyer/CartegorySearch.tsx
  src/components/Common/AppContainer.tsx
  src/components/Common/Header.tsx
  src/components/Common/TabA1.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/styles/GlobalStyle.ts
  src/styles/font.tsx
  src/utils/constant.ts
Labels: Feature, Setting

#7 fix: height scroll 문제 fix (#5)
  src/components/Common/AppContainer.tsx
  src/styles/GlobalStyle.ts
Labels: Bug, Setting

#8 [fix] font family 추가 안했었음(#2)
  src/styles/font.tsx
Labels: Bug, Style, Setting

#9 [Feature] font.tsx padding margin props 추가
  src/styles/font.tsx
Labels: Feature, Setting

#12 [Feature] 판매자 사이드 홈페이지, 내 정보 페이지 UI 작성 및 공통 컴포넌트 작성
  src/Router.tsx
  src/assets/characters/char_공감.svg
  src/assets/characters/char_조언.svg
  src/assets/characters/char_팩폭.svg
  src/assets/icons/info.svg
  src/assets/icons/logo-text.svg
  src/assets/icons/recipt.svg
  src/assets/icons/review-heart.svg
  src/assets/icons/review.svg
  src/assets/icons/right-arrow.svg
  src/assets/icons/save.svg
  src/components/Common/Header.tsx
  src/components/Common/HomeAboutFooterSection.tsx
  src/components/Common/OnGoingConsultSection.tsx
  src/components/Common/OngoingCounsultBox.tsx
  src/components/Common/Profile.tsx
  src/components/Common/TabA1.tsx
  src/components/Seller/ConsultReviewsSection.tsx
  src/components/Seller/IncomeManagementSection.tsx
  src/pages/Seller/SellerHome.tsx
  src/pages/Seller/SellerMypage.tsx
Labels: Feature, Style

#13 [Feature] 홈화면 토글 제외 마무리
  src/assets/icons/icon-down-toggle.svg
  src/assets/icons/icon-heart2.svg
  src/assets/icons/icon-more.svg
  src/assets/icons/icon-save1.svg
  src/assets/icons/icon-save2.svg
  src/components/Buyer/BuyerHome/ConsultInProgress.tsx
  src/components/Buyer/BuyerHome/ConsultInReady.tsx
  src/components/Buyer/Common/CartegorySearch.tsx
  src/components/Buyer/Common/ConsultCard.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/components/Buyer/Common/TagA2Cartegory.tsx
  src/components/Buyer/Common/TagA2Consult.tsx
  src/components/Common/TabA1.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/styles/color.ts
  src/utils/Characters.tsx
  src/utils/type.ts
Labels: Feature, Style, Setting

#14 feat: 로고, 캐릭터 색상 변경 및 공통컴포넌트 TagA2 추가
  src/assets/characters/char1.svg
  src/assets/characters/char2.svg
  src/assets/characters/char3.svg
  src/assets/characters/char4.svg
  src/assets/characters/char5.svg
  src/assets/characters/char6.svg
  src/assets/characters/char7.svg
  src/assets/characters/char8.svg
  src/assets/icons/logo-buyer.svg
  src/assets/icons/logo-seller.svg
  src/components/Buyer/BuyerHome/ConsultInProgress.tsx
  src/components/Buyer/Common/ConsultCard.tsx
  src/components/Common/TagA2Consult.tsx
  src/styles/color.ts
  src/utils/type.ts
Labels: Feature, Style, Setting

#18 [Feature] 상담사 페이지 구현완료
  src/Router.tsx
  src/assets/icons/icon-arrow-back.svg
  src/assets/icons/icon-heart-rate1.svg
  src/assets/icons/icon-heart-rate2.svg
  src/assets/icons/icon-heart-rate3.svg
  src/assets/icons/icon-heart-rate4.svg
  src/assets/icons/icon-heart-rate5.svg
  src/assets/icons/icon-up-toggle.svg
  src/assets/icons/underline-counselor-info.svg
  src/components/Buyer/BuyerCounselorProfile/CounselorExp.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorProfileCard.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorProfileHeader.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorProfileNav.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerCounselorProfile/index.ts
  src/components/Buyer/BuyerHome/ConsultInReady.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/components/Common/TagA2Cartegory.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/utils/HeartRate.tsx
  src/utils/constant.ts
  src/utils/counselorDummy.ts
  src/utils/type.ts
Labels: Bug, Feature, Style

#21 [Feature] 프로필 수정 UI 구현, AppContainer 색상 버그 픽스
  src/Router.tsx
  src/assets/icons/icon-check.svg
  src/components/Common/AppContainer.tsx
  src/components/Common/Input.tsx
  src/components/Common/Profile.tsx
  src/components/Seller/.gitkeep
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileHeader.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/SaveButton.tsx
  src/components/Seller/SellerMyPageViewProfile/ModifyButton.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileHeader.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
  src/hooks/useInput.ts
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/pages/Seller/SellerMyPageViewProfile.tsx
  src/pages/Seller/SellerMypage.tsx
  src/utils/isIncludeSpecialLetter.ts
  src/utils/profileDummy.ts
Labels: Feature, Style

#25 [Feature] 프로필 수정 페이지 모달 구현
  src/Router.tsx
  src/assets/icons/icon-check.svg
  src/components/Buyer/Common/SortModal.tsx
  src/components/Common/Input.tsx
  src/components/Seller/SellerMyPageModifyProfile/CategoryModal.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/SaveButton.tsx
  src/components/Seller/SellerMyPageModifyProfile/StyleModal.tsx
  src/components/Seller/SellerMyPageModifyProfile/TypeModal.tsx
  src/hooks/useCustomSelect.ts
  src/hooks/useInput.ts
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/utils/atom.ts
  src/utils/categoryInputmaker.ts
  src/utils/isIncludeSpecialLetter.ts
  src/utils/profileDummy.ts
Labels: Feature, Style

#32 [Feature] 판매자 편지 페이지, 상담 시간 선택과 은행 선택을 제외하고 구현 #11
  src/assets/icons/graphic-update-success.svg
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/UpdatePopup.tsx
  src/components/Seller/SellerMyPageModifyProfile/UpdateSuccess.tsx
  src/hooks/useInput.ts
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/utils/atom.ts
  src/utils/profileDummy.ts
Labels: Feature

#36 [Feature] 마인더 인증
  src/Router.tsx
  src/assets/icons/grahpic-verify-success.svg
  src/assets/icons/graphic-verify-fail.svg
  src/assets/icons/graphic-verify-material-1.svg
  src/assets/icons/graphic-verify-material-2.svg
  src/assets/icons/graphic-verify-material-3.svg
  src/assets/icons/graphic-verify-material-4.svg
  src/components/Common/BackDrop.tsx
  src/components/Common/TabB2.tsx
  src/components/Seller/Common/BottomButton.tsx
  src/components/Seller/Common/ProgressStatus.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteHeader.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileHeader.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
  src/components/Seller/SellerVerifyMaterial/FinalMaterial.tsx
  src/components/Seller/SellerVerifyMaterial/FirstMaterial.tsx
  src/components/Seller/SellerVerifyMaterial/IsTakeQuizModal.tsx
  src/components/Seller/SellerVerifyMaterial/SecondMaterial.tsx
  src/components/Seller/SellerVerifyMaterial/ThirdMaterial.tsx
  src/components/Seller/SellerVerifyMaterial/VerifyMaterialButton.tsx
  src/components/Seller/SellerVerifyMaterial/VerifyMaterialHeader.tsx
  src/components/Seller/SellerVerifyQuiz/IsStopQuizModal.tsx
  src/components/Seller/SellerVerifyQuiz/IsSubmitQuizModal.tsx
  src/components/Seller/SellerVerifyQuiz/QuestionBox.tsx
  src/components/Seller/SellerVerifyQuiz/VerifyFail.tsx
  src/components/Seller/SellerVerifyQuiz/VerifyQuizButton.tsx
  src/components/Seller/SellerVerifyQuiz/VerifyQuizHeader.tsx
  src/components/Seller/SellerVerifyQuiz/VerifySuccess.tsx
  src/pages/Seller/SellerVerifyMaterial.tsx
  src/pages/Seller/SellerVerifyQuiz.tsx
  src/utils/atom.ts
  src/utils/constant.ts
Labels: Feature, Style

#37 [Feature]결제 내역 페이지 구현 완료
  src/Router.tsx
  src/components/Buyer/BuyerHome/ConsultInReady.tsx
  src/components/Buyer/BuyerLetter/LetterTags.tsx
  src/components/Buyer/BuyerPayment/PaymentCard.tsx
  src/components/Buyer/BuyerPayment/PaymentModal.tsx
  src/components/Buyer/BuyerReviewManage/ReviewManageCard.tsx
  src/components/Buyer/Common/SearchResults.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerLetter.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Buyer/BuyerWriteReview.tsx
  src/utils/atom.ts
  src/utils/buyerDummy.ts
Labels: Feature, Style

#40 [Feature] 은행 선택 모달 구현
  src/assets/icons/bank/bnk.svg
  src/assets/icons/bank/city.svg
  src/assets/icons/bank/dgb.svg
  src/assets/icons/bank/gwangju.svg
  src/assets/icons/bank/hana.svg
  src/assets/icons/bank/ibk.svg
  src/assets/icons/bank/jeju.svg
  src/assets/icons/bank/kakaobank.svg
  src/assets/icons/bank/kb.svg
  src/assets/icons/bank/kbank.svg
  src/assets/icons/bank/kdb.svg
  src/assets/icons/bank/newtown.svg
  src/assets/icons/bank/nh.svg
  src/assets/icons/bank/post-office.svg
  src/assets/icons/bank/saving.svg
  src/assets/icons/bank/scjail.svg
  src/assets/icons/bank/shinhan.svg
  src/assets/icons/bank/sinhyeop.svg
  src/assets/icons/bank/suhyeop.svg
  src/assets/icons/bank/toss.svg
  src/assets/icons/bank/wuri.svg
  src/components/Seller/SellerMyPageModifyProfile/BankSelectModal.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/utils/BankIcon.tsx
  src/utils/constant.ts
Labels: Feature, Style

#42 [Feature] 헤더 변경 및 디자인 수정, 폰트 깜빡임 수정
  src/assets/icons/logo-buyer.svg
  src/assets/icons/logo-seller.svg
  src/assets/icons/logo-text.svg
  src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerHome/ConsultInProgress.tsx
  src/components/Buyer/BuyerSearch/SearchHeader.tsx
  src/components/Buyer/BuyerSearch/SearchRecent.tsx
  src/components/Common/Header.tsx
  src/index.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerLogout.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
  src/pages/Buyer/BuyerTerminate.tsx
  src/styles/GlobalStyle.ts
  src/styles/font.css
  src/styles/font.tsx
Labels: Feature, Style

#45 [Feature] 로그인, 회원가입 구현 및 jwt 보안 관련 코드 작성
  package-lock.json
  package.json
  src/Router.tsx
  src/api/axios.ts
  src/api/get.ts
  src/api/post.ts
  src/assets/icons/graphic-payment-complete.svg
  src/assets/icons/icon-payment-detail-heart.svg
  src/components/Buyer/BuyerConsult/ConsultModal.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorProfileHeader.tsx
  src/components/Buyer/BuyerHome/ConsultInReady.tsx
  src/components/Buyer/BuyerPaymentDetail/PaymentDetailFooter.tsx
  src/components/Buyer/BuyerPaymentDetail/PaymentDetailInfo.tsx
  src/components/Buyer/BuyerSignup/SignupInfo.tsx
  src/components/Buyer/BuyerSignup/SignupPw.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/components/Common/AppContainer.tsx
  src/hooks/useInput.ts
  src/hooks/useTokenRefresh.tsx
  src/index.tsx
  src/pages/Buyer/BuyerAvailCounselor.tsx
  src/pages/Buyer/BuyerConsultRequest.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerPaymentComplete.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
  src/pages/Buyer/BuyerSignup.tsx
  src/pages/Buyer/BuyerWriteReview.tsx
  src/utils/atom.ts
  src/utils/constant.ts
  src/utils/cookie.ts
Labels: API, Feature, Refactor, Style

#49 [Feature] 로그인 interceptor로 변경
  .gitignore
  src/Router.tsx
  src/api/axios.ts
  src/api/get.ts
  src/api/post.ts
  src/assets/icons/graphic-payment-inprocess.svg
  src/components/Buyer/BuyerPaymentDetail/PaymentDetailFooter.tsx
  src/components/Buyer/BuyerSignup/SignupInfo.tsx
  src/components/Common/AppContainer.tsx
  src/components/Common/Button.tsx
  src/hooks/useTokenRefresh.tsx
  src/pages/Buyer/BuyerConsultRequest.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerPaymentComplete.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
  src/utils/constant.ts
Labels: Bug, API, Feature

#56 [Feature] 편지 구현 중간 pr
  .gitignore
  src/api/axios.ts
  src/api/get.ts
  src/api/patch.ts
  src/api/post.ts
  src/components/Buyer/BuyerConsult/ConsultModal.tsx
  src/components/Buyer/BuyerHome/ConsultInProgress.tsx
  src/components/Buyer/BuyerLetter/LetterMainSection.tsx
  src/components/Buyer/BuyerLetterWrite/LetterLoadModal.tsx
  src/components/Buyer/BuyerLetterWrite/LetterSaveModal.tsx
  src/components/Buyer/BuyerLetterWrite/LetterWriteModal.tsx
  src/components/Buyer/Common/ConsultCard.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerLetter.tsx
  src/pages/Buyer/BuyerLetterWrite.tsx
  src/pages/Common/Admin.tsx
  src/utils/convertCategoryEnum.tsx
Labels: API, Feature

#57 [Feature] 편지 페이지 임시저장까지 완료
  src/api/patch.ts
  src/components/Buyer/BuyerLetterWrite/LetterSaveModal.tsx
  src/components/Buyer/BuyerLetterWrite/LetterWriteModal.tsx
  src/pages/Buyer/BuyerLetter.tsx
  src/pages/Buyer/BuyerLetterWrite.tsx
Labels: API, Feature

#58 상담사 편지 API 연동, 퀴즈 API 연동 (POST)
  src/api/get.ts
  src/api/post.ts
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerLetter/LetterBonusQuestionStep.tsx
  src/components/Seller/SellerLetter/LetterBonusReplyStep.tsx
  src/components/Seller/SellerLetter/LetterQuestionStep.tsx
  src/components/Seller/SellerLetter/LetterReplyStep.tsx
  src/components/Seller/SellerLetterWrite/LetterIsSaveModal.tsx
  src/components/Seller/SellerLetterWrite/LetterPostModal.tsx
  src/components/Seller/SellerLetterWrite/LetterSavePostModal.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteHeader.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
  src/components/Seller/SellerVerifyQuiz/IsSubmitQuizModal.tsx
  src/pages/Seller/SellerLetter.tsx
  src/pages/Seller/SellerLetterWrite.tsx
Labels: API

#60 [Feature] 구매자 편지 완료
  src/api/axios.ts
  src/components/Buyer/BuyerLetter/LetterMainSection.tsx
  src/components/Buyer/BuyerLetterWrite/LetterLoadModal.tsx
  src/components/Buyer/BuyerLetterWrite/LetterPostModal.tsx
  src/components/Buyer/BuyerSignup/SignupInfo.tsx
  src/components/Buyer/BuyerSignup/SignupModal.tsx
  src/components/Buyer/BuyerSignup/SignupPw.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/components/Buyer/Common/ConsultCard.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerLetter.tsx
  src/pages/Buyer/BuyerLetterWrite.tsx
  src/styles/font.tsx
  src/utils/LoadingSpinner.tsx
  src/utils/atom.ts
  src/utils/type.ts
Labels: API, Feature

#64 [Feature] 로그인, 회원가입, 로그아웃, 어드민 페이지 최종완료
  package-lock.json
  package.json
  src/Router.tsx
  src/api/get.ts
  src/api/patch.ts
  src/components/Buyer/BuyerLogin/LoginModal.tsx
  src/components/Buyer/BuyerSearch/SearchRecent.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerLogout.tsx
  src/pages/Common/Admin.tsx
  src/utils/atom.ts
Labels: API, Feature

#70 마인더 판매정보 섹션 API 예외처리 및 자잘한 디자인 반영
  src/components/Common/Input.tsx
  src/components/Common/Profile.tsx
  src/components/Seller/Common/BottomButton.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileHeader.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/StyleModal.tsx
  src/components/Seller/SellerMyPageViewProfile/NoProfileSection.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileHeader.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
  src/hooks/useCustomSelect.ts
  src/hooks/useInput.ts
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/pages/Seller/SellerMyPageViewProfile.tsx
  src/pages/Seller/SellerVerifyQuiz.tsx
Labels: API, Style

#75 [Feature] 판매정보 시간 선택 구현중..
  src/assets/icons/icon-check2.svg
  src/assets/icons/icon-minus.svg
  src/assets/icons/icon-plus.svg
  src/assets/icons/likelionSogangLogo.png
  src/components/Common/Input.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerHome/ConsultReviewsSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/CategoryModal.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileHeader.tsx
  src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
  src/utils/atom.ts
Labels: Feature

#76 [Feature] 상담 시간 선택 완전히 구현, 편지 보충, API 주소 바뀐 것 반영
  src/api/get.ts
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/IsOutPopup.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileHeader.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
  src/components/Seller/SellerMyPageModifyProfile/UpdatePopup.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/pages/Seller/SellerMyPageViewProfile.tsx
  src/utils/atom.ts
  src/utils/convertTimeToString.ts
  src/utils/formatTimeRange.ts
Labels: API, Feature

#78 [Feature] 바뀐 상담 api 주소 반영 및 웹소켓 package 수정
  package.json
  src/Router.tsx
  src/api/get.ts
  src/api/patch.ts
  src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
  src/components/Buyer/BuyerCategoryResult/CategoryResultHeader.tsx
  src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
  src/components/Buyer/BuyerLetterWrite/LetterLoadModal.tsx
  src/components/Buyer/Common/CartegorySearch.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/pages/Buyer/BuyerAvailCounselor.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/pages/Buyer/BuyerLetterWrite.tsx
  src/socket.d.ts
  src/utils/type.ts
Labels: API, Feature

#82 feat: 요일 불필요하게 뜨는 문제 해결 (#46)
  src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
  src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
  src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
  src/components/Buyer/BuyerSearchResult/SearchResults.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/utils/atom.ts
  src/utils/type.ts
Labels: API, Feature

#83 [Bug] 요일 문제해결
  src/components/Buyer/BuyerAvailCounselor/AvailCounselorSearchResult.tsx
  src/components/Buyer/BuyerCategoryResult/CategorySearchResult.tsx
  src/components/Buyer/BuyerHome/HomeConsultInReady.tsx
  src/components/Buyer/BuyerSearchResult/SearchResults.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/utils/atom.ts
  src/utils/type.ts
Labels: API, Feature

#84 [fix] 상담 결제하기 연동 및 회원가입 이메일 maxlength 수정
  src/Router.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/pages/Buyer/BuyerConsultRequest.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
  src/pages/Seller/SellerPwChange.tsx
Labels: Bug, API, Feature

#85 [Fix] 상담 결제하기 연동, 회원가입 max length 수정
  src/Router.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorFooter.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/pages/Buyer/BuyerConsultRequest.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerPaymentDetail.tsx
  src/pages/Seller/SellerPwChange.tsx
Labels: Bug, API

#91 [Feature] 내정보 페이지 구매자 구현완료 및 public instance 추가
  src/api/axios.ts
  src/api/get.ts
  src/api/post.ts
  src/components/Buyer/BuyerSearch/SearchHeader.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerMypage.tsx
Labels: API, Feature

#95 [Feature] 마인더 프로필 페이지 구현 및 상담사 카드 오류 수정
  src/api/get.ts
  src/api/patch.ts
  src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorProfileCard.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/Common/ReadyConsultCard.tsx
  src/components/Buyer/Common/SearchResults.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
  src/utils/type.ts
Labels: Bug, API, Feature

#97 [Featrue] 채팅 시작, 몇가지 예외처리
  package-lock.json
  package.json
  src/components/Seller/SellerChat/ChatBottomSection.tsx
  src/components/Seller/SellerChat/ChatListSection.tsx
Labels: Feature, Style

#102 [Feature] 채팅 라이브러리 import 성공
  package-lock.json
  package.json
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/pages/Buyer/BuyerChat.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Buyer/BuyerSavedCounselor.tsx
  src/socket.d.ts
Labels: Bug, API, Feature

#104 [Feature] 편지 로직 수정 및 URL 수정
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/Router.tsx
  src/assets/icons/fabicon-big.svg
  src/components/Common/AppContainer.tsx
  src/components/Common/Header.tsx
  src/components/Common/Profile.tsx
  src/components/Common/TabA1.tsx
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerCalculateManagement/ManagementHeader.tsx
  src/components/Seller/SellerCalculateManagement/SellerManagementModal.tsx
  src/components/Seller/SellerChat/ChatBottomSection.tsx
  src/components/Seller/SellerChat/ChatHeader.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerHome/ConsultReviewsSection.tsx
  src/components/Seller/SellerHome/IncomeManagementSection.tsx
  src/components/Seller/SellerHome/OnGoingConsultSection.tsx
  src/components/Seller/SellerLetter/LetterHeader.tsx
  src/components/Seller/SellerMyPageReview/SellerReviewHeader.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileHeader.tsx
  src/components/Seller/SellerVerifyQuiz/VerifyQuizHeader.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Common/Service.tsx
  src/pages/Seller/SellerAccountSetting.tsx
  src/pages/Seller/SellerCalculateManagement.tsx
  src/pages/Seller/SellerConsult.tsx
  src/pages/Seller/SellerHome.tsx
  src/pages/Seller/SellerLetter.tsx
  src/pages/Seller/SellerLogout.tsx
  src/pages/Seller/SellerMyPageViewProfile.tsx
  src/pages/Seller/SellerMypage.tsx
  src/pages/Seller/SellerPwChange.tsx
  src/pages/Seller/SellerRefundBankAccount.tsx
  src/pages/Seller/SellerTerminate.tsx
Labels: API, Style

#109 [Feature] 디자인 자잘한 수정
  src/components/Common/Input.tsx
  src/components/Common/TagLetterStatus.tsx
  src/components/Seller/Common/OngoingCounsultBox.tsx
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerLetter/LetterTagListSection.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/ModifyProfileMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/SetChatTimeSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
  src/components/Skeleton/ConsultCardSkeleton.tsx
  src/pages/Seller/SellerLetter.tsx
  src/pages/Seller/SellerMyPageModifyProfile.tsx
  src/pages/Seller/SellerMyPageViewProfile.tsx
Labels: Feature, Style

#115 [Feature] intersection observer 커스텀 훅 추가 및 마인더프로필 페이지 무한스크롤 구현완료
  src/api/axios.ts
  src/api/get.ts
  src/api/patch.ts
  src/components/Buyer/BuyerCounselorProfile/CounselorInfo.tsx
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/components/Buyer/BuyerLetter/LetterMainSection.tsx
  src/components/Buyer/BuyerPayment/PaymentCard.tsx
  src/components/Buyer/BuyerPayment/PaymentModal.tsx
  src/components/Buyer/BuyerSignup/SignupVerifyEmail.tsx
  src/components/Buyer/Common/ConsultCard.tsx
  src/hooks/useIntersectionObserver.ts
  src/pages/Buyer/BuyerAvailCounselor.tsx
  src/pages/Buyer/BuyerCategoryResult.tsx
  src/pages/Buyer/BuyerConsult.tsx
  src/pages/Buyer/BuyerCounselorProfile.tsx
  src/pages/Buyer/BuyerHome.tsx
  src/pages/Buyer/BuyerLetter.tsx
  src/pages/Buyer/BuyerLetterWrite.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerPayment.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
  src/pages/Common/Admin.tsx
  src/utils/type.ts
Labels: API, Feature

#117 [Feature] 비밀번호 변경 api 연동 완료 및 리뷰관리 페이지 무한스크롤 구현
  src/api/patch.ts
  src/api/post.ts
  src/components/Buyer/BuyerCounselorProfile/CounselorReview.tsx
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
  src/pages/Buyer/BuyerLogin.tsx
  src/pages/Buyer/BuyerPwChange.tsx
  src/pages/Buyer/BuyerReviewManage.tsx
Labels: API, Feature

#118 [Feature] 판매자 profile_Status 에 따른 페이지 접근 권한 부여 및 편지 추가된 API 연동
  src/components/Seller/SellerConsult/SellerConsultSection.tsx
  src/components/Seller/SellerLetter/LetterHeader.tsx
  src/components/Seller/SellerLetterWrite/LetterWriteMainSection.tsx
  src/components/Seller/SellerMyPageModifyProfile/TimeSelectModal.tsx
  src/components/Seller/SellerMyPageReview/SellerReviewMainSection.tsx
  src/components/Seller/SellerMyPageViewProfile/NoProfileSection.tsx
  src/components/Seller/SellerMyPageViewProfile/ViewProfileMainSection.tsx
  src/pages/Seller/SellerLetter.tsx
  src/pages/Seller/SellerMyPageModifyProfile.tsx
Labels: Bug, API

#120 [Feature] chore 서비스 소개 navigate 추가
  src/components/Common/AppContainer.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
Labels: API, Feature

#121 [Feature] chore 서비스 소개 navigate 추가
  src/components/Common/AppContainer.tsx
  src/pages/Buyer/BuyerMypage.tsx
  src/pages/Buyer/BuyerSearchResult.tsx
Labels: API, Feature

#123 [Fix] 진행 중인 상담 0일 시 오류 해결
  src/components/Buyer/BuyerHome/HomeConsultInProgress.tsx
Labels: Bug, API
